### ISSUE TITLE
Reference Architecture snapshot has typo

### ISSUE THREAD

**Issue by SunnyOswal** [Microsoft/almvm#103]
URL: https://almvm.azurewebsites.net/labs/vstsextend/kubernetes/

Reference architecture snapshot has "Azure Container **Service** (Registry)" label for the registry. 

Instead it should be either "Azure Container **Registry** (ACR)" or "Azure Container **Registry** (Registry)"

**Comment by sriramdasbalaji** [comment]
Hi @SunnyOswal ,

Thanks for reporting this. Now we have updated the reference architecture diagram.

Thanks
Balaji

**Comment by SunnyOswal** [comment]
Thanks
