### ISSUE TITLE
The link for "Launch the virtual machine" is broken

### ISSUE THREAD

**Issue by snowstormlife** [Microsoft/almvm#105]
In "https://github.com/Microsoft/almvm/tree/master/labs/vsts/selenium/readme.md" the link for "Launch the virtual machine" is broken. It simply points back to "https://almvm.azurewebsites.net/labs/vsts/selenium/" instead of a VM.

**Comment by sriramdasbalaji** [comment]
Hi @snowstormlife 

Thanks for reporting this issue. We will fix the link for Virtual Machine asap.

Thanks
Balaji

**Comment by sriramdasbalaji** [comment]
Hi @snowstormlife 
The link for "Launch the virtual machine" is fixed now. 

Thanks
Balaji
