### ISSUE TITLE
Request: Add "Last Update: MM/DD/YYYY" at the top of the labs pages

### ISSUE THREAD

**Issue by dburnison** [Microsoft/almvm#26]
It would be great to see "Last Update: MM/DD/YYYY" at the top of the following pages, (similar to what we now see on the documentation pages such as https://www.visualstudio.com/en-us/docs/alm-devops-features). 

- https://almvm.azurewebsites.net//labs/tfs/
- https://almvm.azurewebsites.net//labs/tfs/technet/
- https://almvm.azurewebsites.net//labs/vsts/

This would help users track if new labs are available since they last visited one of these pages.

**Comment by SrivatsaMarichi** [comment]
That's a good suggestion, noted. We have it for TFS, will include that for VSTS labs :-)
