### ISSUE TITLE
Missing step or wrong information.

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/almvm#5]
on https://microsoft.github.io/almvm/labs/vsts/agile/#exercise-3-working-with-kanban-board 

Step 4. "_Click the New Commit column. Set the WIP Limit to 3._" 
You can't set WIP to New or Done. Unless the instruction mean to create a new column "Commit" and set the WIP to 3

**Comment by hsachinraj** [comment]
That should be "Develop" column instead. The "Develop" column was initially called "New commit" which was renamed later. Thanks for the catch.
