### ISSUE TITLE
Missing information in "Enabling Continuous Delivery" lab

### ISSUE THREAD

**Issue by simbi** [Microsoft/almvm#71]
In Task 2 in Exercise 3 in the "Enabling Continuous Delivery" lab the configuration for the Source in  Windows Machine File Copy task is missing \Dev\ in the path. 

I configured the path as the instructions said to: 
$(Build.Repository.LocalPath)\FabrikamFiber.CallCenter\FabrikamFiber.Web
But the build failed. So I checked the path and at least on my ALMVM the correct path is
$(Build.Repository.LocalPath)\Dev\FabrikamFiber.CallCenter\FabrikamFiber.Web

**Comment by SrivatsaMarichi** [comment]
@simbi Thanks for noticing and reporting. Yes the build fails because the **Dev** parameter in the Source property is missing. Will update the same. Thanks :-)
