### ISSUE TITLE
'Deploy application to AKS using Kubernetes' TFS.WebApi.Exception error

### ISSUE THREAD

**Issue by xerosum** [Microsoft/almvm#88]
TFS.WebApi.Exception: The Url specified for parameter notmyrealaksname.hcp.westeurope.azmk8s.io is not valid. Parameter name: endpoint.Url 

When copying the config file generated by az aks get-credentials, as per https://almvm.azurewebsites.net/labs/vstsextend/kubernetes/

Tried on a couple of different machines.

**Comment by sriramdasbalaji** [comment]
Hi Xerosum,
While creating the Kubernetes endpoint, in the **URL** please prefix **http://** before mentioning your aks url. 
Example: http://notmyrealaksname.hcp.westeurope.azmk8s.io

Thanks
