### ISSUE TITLE
'Deploy application to AKS using Kubernetes' part 2 - parameters not editable

### ISSUE THREAD

**Issue by xerosum** [Microsoft/almvm#92]
Out of the box the parameters for the build definition are not editable. They just contain informational links.

![aks-vsts](https://user-images.githubusercontent.com/2227211/39858336-ef309960-543e-11e8-8d9e-53139765b5dc.jpg)

**Comment by visheshbalani** [comment]
Yes, can anyone help us on this?

**Comment by visheshbalani** [comment]
Hi, @xerosum did you figure out a way to get those options of Azure subscription and Azure Container Registry?

**Comment by xerosum** [comment]
Hi @visheshbalani It looks like a mismatch between the VSTS that was used to create the tutorial and what's currently available -- even with all relevant preview options turned on, there is no option to hook in process parameters for the agent (there should be a 'link' option when you click the 'i' next to Agent queue). 

Also, the documentation page for this feature https://docs.microsoft.com/en-us/vsts/pipelines/archive/preview/2017-user-experience?view=vsts#parameters has broken image links.

Any ideas @sriramdasbalaji or @SrivatsaMarichi?

**Comment by sriramdasbalaji** [comment]
Hi @xerosum and @visheshbalani ,

Sorry for the delay in response.  You will get those options( **AzureSubscription** and  **Azure Container Registry**) when you select Docker tasks in the build definition. Earlier we used to get these options at process level  which will be linked to all relevant tasks.  Now may be mismatch of VSTS version or REST API version we are not getting. We will check this out.

Thanks
Balaji
